# Change these first
owner: kevlopzz
repo: Status

sites:
  - name: NateTech
    url: https://www.natetech.dev
  - name: Aneudy Adames
    url: https://www.aneudyadames.dev
  - name: Just Married
    url: https://just-married.us/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /Status
  baseUrl: /kevlopzz/Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime - Status
  #introTitle: "**Upptime** Status Sites."
  #introMessage: Status de uptime de los sitios 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
